# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.3
_src_path: gh:algorandfoundation/algokit-python-template
author_email: dictforum@gmail.com
author_name: jorniks
contract_name: farm_shield
deployment_language: python
preset_name: starter
project_name: farm-shield-contracts

