# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.12
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: dictforum@gmail.com
author_name: jorniks
cloud_provider: none
contract_name: farm_shield
deployment_language: python
preset_name: production
project_name: farm-shield

